name: Crete Pre-Release Page

on:
  push:
    tags:
      - '*'
  workflow_dispatch: {}

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - .
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cache
        uses: actions/cache@v3.3.2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          draft: true
          generate_release_notes: true
          name: ${{ github.event.pull_request.body }}
          tag_name: ${{ github.event.pull_request.title }}
          prerelease: false
          files: |
            build/${{ env.FILE_NAME }}.unitypackage